### ISSUE TITLE
Fix date not updating until reload

### ISSUE THREAD

**Issue by gperinazzo** [devraccoon/tago#16]
**Expected behaviour**
After updating the date on ```DueDateBox > DatePicker```, the date shown will be the new one on later views of that tag.

**Observed behaviour**
DatePicker is not changing the date when you reopen the tag, unless you reload the page.

**How to reproduce**
Open a tag, change its due date, close the modal, then reopen it. The date displayed is the old one.

**Comment by rgcalsaverini** [comment]
Fixed
